name: Build Arch Linux ISO

on:
  push:
    branches:
      - main  # Запускать сборку при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Ubuntu как базовую систему

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Оптимизация для быстрого клонирования

      - name: Set up Docker
        run: |
          echo "Удаление конфликтующего пакета containerd..."
          sudo apt remove --purge containerd
          echo "Установка Docker..."
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          echo "Добавление пользователя в группу docker..."
          sudo usermod -aG docker $USER
          echo "✅ Docker установлен и настроен."

      - name: Run build script
        run: |
          chmod +x build-arch.sh
          ./build-arch.sh
          sudo chown -R $USER:$USER my-archiso

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux.iso
          path: my-archiso/out/*.iso
          if-no-files-found: error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
