name: Build Arch Linux ISO

on:
  push:
    branches:
      - main  # Запускать сборку при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Ubuntu как базовую систему

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up Docker
        run: |
          # Удаляем конфликтующий пакет containerd
          sudo apt remove --purge containerd
          # Устанавливаем Docker с помощью официального скрипта
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          # Добавляем пользователя в группу docker
          sudo usermod -aG docker $USER

      - name: Run build script
        run: |
          chmod +x build-arch.sh
          ./build-arch.sh
          sudo chown -R $USER:$USER my-archiso

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux.iso
          path: my-archiso/out/*.iso  # Загружаем собранный ISO как артефакт
